---
apiVersion: v1
kind: Service
metadata:
  name: mango-server-svc
spec:
  type: NodePort
  ports:
    - name: http-mango-server
      port: 8080
      targetPort: 8080
  selector:
    app: mango-server
    tier: mango-server
